add_newline = false
palette = "catppuccin_mocha"

format = "$username$hostname$directory$git_branch$git_status$nodejs$python$golang$rust$time$line_break$character"

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"

[username]
show_always = true
format = "[$user](rosewater)[@](overlay0)"

[hostname]
ssh_only = false
format = "[$hostname](mauve) "
trim_at = "-"
disabled = false

[directory]
truncation_length = 5
format = "[$path](blue)[$read_only](red) "

[git_branch]
symbol = "git:"
format = "[$symbol$branch](lavender) "

[git_status]
format = "([$all_status$ahead_behind](yellow) )"

[nodejs]
symbol = "node:"
format = "[$symbol($version )](green)"

[python]
symbol = "py:"
format = "[$symbol$version](yellow) "

[golang]
symbol = "go:"
format = "[$symbol$version](teal) "

[rust]
symbol = "rs:"
format = "[$symbol$version](peach) "

[time]
disabled = false
time_format = "%H:%M"
format = "[$time](subtext0) "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext0 = "#a6adc8"
overlay0 = "#6c7086"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"